### ISSUE TITLE
Allow one space

### ISSUE THREAD

**Issue by cedvan** [nochso/html-compress-twig#5]
Hi,

it would be must to be able :

``` html
<ul> <ul>     =>     </ul> </ul>   # Keep because one space
```

``` html
<ul>  <ul>    =>     </ul></ul>   # Compress because more one space
```

Thank you for job ;)

**Comment by nochso** [comment]
Oh, don't thank _me_ :)

This library is only a Twig extension, the actual compression is done by [WyriHaximus/HtmlCompress](https://github.com/WyriHaximus/HtmlCompress). See [class HtmlCompressor](https://github.com/WyriHaximus/HtmlCompress/blob/master/src/Compressor/HtmlCompressor.php)
