### ISSUE TITLE
PhpUnit - Remaining deprecation notices

### ISSUE THREAD

**Issue by orangevinz** [nochso/html-compress-twig#6]
Hi,

Thanks for this extension 👍 

Symfony : 2.8.12
PhpUnit : 5.6.1

Phpunit returns this error:
"Referencing the "nochso\HtmlCompressTwig\Extension" extension by its name (defined by getName()) is deprecated since 1.26 and will be removed in Twig 2.0. Use the Fully Qualified Extension Class Name instead:"

I think you just have to : 
- remove the getName() in Extension.php line 69
- call the extension like : Extension::class in MinifyHtmlNode.php line 28

;-)

Vinz

**Comment by nochso** [comment]
Thanks for the report! I'll have to look at it later because I can't get `composer install` to finish. Seems Github is having issues at the moment.

**Comment by nochso** [comment]
I've pushed a commit that deprecates NAME and getName, using ::class instead.

However I'm hesitant to tag this because of failing tests: https://travis-ci.org/nochso/html-compress-twig/builds/169690696

Not sure whether this change is related, but tests are currently failing with lowest dependency versions..

**Comment by orangevinz** [comment]
Indeed and I can't understand why too... sorry ;-)

**Comment by rodush** [comment]
And now it is time of symfony 3.2... which generates a lot of deprecation warnings in Twig. Any plans to update it to support latest versions of twig + symfony?
This extension is really useful! it is a pity I had to wipe it out from our project's dependencies...

**Comment by nochso** [comment]
I'll have another look this weekend. See my last comment for the failing tests if you'd like to help out.

**Comment by nochso** [comment]
Fixed in 2.0.0 which was just released.
