### ISSUE TITLE
Deprecation warninng

### ISSUE THREAD

**Issue by dspiegel** [nochso/html-compress-twig#7]
Getting deprecation warning:

`Referencing the "HtmlCompressTwig" extension by its name (defined by getName()) is deprecated since 1.26 and will be removed in Twig 2.0. Use the Fully Qualified Extension Class Name instead.`

Line 28 of MinifyHtmlNode.php is:
            `->write('$extension = $this->env->getExtension(\'' . Extension::NAME . '\');' . "\n")`

Needs to be something like this:
           ` ->write('$extension = $this->env->getExtension(\'nochso\HtmlCompressTwig\Extension\');' . "\n")`

I made this change to local copy and deprecation warning was gone.

or Extension::NAME constant can be changed to 'nochso\HtmlCompressTwig\Extension'

Current twig version:
`twig/extensions   v1.4.1` 
`twig/twig   v1.31.0 `

Thanks, Dave

**Comment by nochso** [comment]
This was fixed by release 2.0.0 a few weeks ago. See #6

**Comment by dspiegel** [comment]
@nochso 
Sorry about that. #6 title indicated PhpUnit issue so I didn't look at it as my issue has nothing to do with PhpUnit.

My composer.json was set to version ^1.0 so didn't pick up change. I have updated to ^2.0. No more deprecation notices.

Thanks

**Comment by nochso** [comment]
No problem. I just learned about it, but check out [`composer outdated`](https://getcomposer.org/doc/03-cli.md#outdated). I'd have recommended climb, but it was deprecated in favor of composer's command.
