### ISSUE TITLE
Support Twig 2.0

### ISSUE THREAD

**Issue by benzon** [nochso/html-compress-twig#8]
Any chance you will update this to support Twig 2.x?

**Comment by benzon** [comment]
Just did a VCS test and it's working fine with Twig 2.x no issues there, only thing i did was allow the 2.0 branche to be used, right now it's set to 2.0 and above.

But ye all you got to do is just allow version 2.x

**Comment by benzon** [comment]
You should be safe to do a Pull request of my fork.

what i changed is not a lot.

"php" : "^5.6 || ^7.0",
"wyrihaximus/html-compress": "^1.1",
"twig/twig": "^1.26 || ^2.0"

Noticed in your yml that you had php requirements so added it to the composer.json.

**Comment by nochso** [comment]
Thank you for looking into it.

I'll test it as soon as my connection is reliable enough for running composer.

**Comment by benzon** [comment]
One thing i noticed, the function is not getting cached, so it's actually slowing things down when used, insted of speeding up in the end.

**Comment by nochso** [comment]
> One thing i noticed, the function is not getting cached

How would that work? What would I use as a key for caching the compressed output?

You're probably better off caching at the HTTP layer.

**Comment by nochso** [comment]
I've added `^2.0` to the Twig version constraint and Travis is cool with it. The change is in release [2.0.1](https://github.com/nochso/html-compress-twig/releases/tag/2.0.1).


Regarding caching/performance, feel free to open another issue.
